### ISSUE TITLE
Documenting constants

### ISSUE THREAD

**Issue by jamesarosen** [kneath/kss#98]
I'd like to document the constants that my `.scss` file makes available. For example, something like the following:

``` scss
// Body Text
//
// The main body text.
//
// Usage: .my-rule: { font-family: $font-body-text; }
//
// Styleguide 1.0.5
$font-body-text: "Comic Sans", Tahoma, sans-serif;
```
